[2025-05-07T15:36:34.263+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_lake_pipeline.transform_csv manual__2025-05-07T15:36:33.053231+00:00 [queued]>
[2025-05-07T15:36:34.271+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_lake_pipeline.transform_csv manual__2025-05-07T15:36:33.053231+00:00 [queued]>
[2025-05-07T15:36:34.274+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-07T15:36:34.276+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-05-07T15:36:34.277+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-07T15:36:34.286+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): transform_csv> on 2025-05-07 15:36:33.053231+00:00
[2025-05-07T15:36:34.292+0000] {standard_task_runner.py:55} INFO - Started process 177 to run task
[2025-05-07T15:36:34.295+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'transform_csv', 'manual__2025-05-07T15:36:33.053231+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_pipeline.py', '--cfg-path', '/tmp/tmp3jwium3x']
[2025-05-07T15:36:34.298+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask transform_csv
[2025-05-07T15:36:34.314+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-07T15:36:34.369+0000] {task_command.py:389} INFO - Running <TaskInstance: data_lake_pipeline.transform_csv manual__2025-05-07T15:36:33.053231+00:00 [running]> on host 27395cff6f3f
[2025-05-07T15:36:34.602+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_lake_pipeline
AIRFLOW_CTX_TASK_ID=transform_csv
AIRFLOW_CTX_EXECUTION_DATE=2025-05-07T15:36:33.053231+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-07T15:36:33.053231+00:00
[2025-05-07T15:36:34.614+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_lake_pipeline.py", line 15, in transform_csv
    df = pd.read_csv(input_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
[2025-05-07T15:36:34.626+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=data_lake_pipeline, task_id=transform_csv, execution_date=20250507T153633, start_date=20250507T153634, end_date=20250507T153634
[2025-05-07T15:36:34.635+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task transform_csv (No columns to parse from file; 177)
[2025-05-07T15:36:34.684+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-07T15:36:34.702+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
