[2025-05-07T15:30:55.413+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: csv_etl_dag.transform_csv manual__2025-05-07T15:30:54.625485+00:00 [queued]>
[2025-05-07T15:30:55.421+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: csv_etl_dag.transform_csv manual__2025-05-07T15:30:54.625485+00:00 [queued]>
[2025-05-07T15:30:55.422+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-07T15:30:55.423+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-05-07T15:30:55.424+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-07T15:30:55.434+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): transform_csv> on 2025-05-07 15:30:54.625485+00:00
[2025-05-07T15:30:55.439+0000] {standard_task_runner.py:55} INFO - Started process 208 to run task
[2025-05-07T15:30:55.443+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'csv_etl_dag', 'transform_csv', 'manual__2025-05-07T15:30:54.625485+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_pipeline.py', '--cfg-path', '/tmp/tmpt5pj4zmx']
[2025-05-07T15:30:55.445+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask transform_csv
[2025-05-07T15:30:55.461+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-07T15:30:55.515+0000] {task_command.py:389} INFO - Running <TaskInstance: csv_etl_dag.transform_csv manual__2025-05-07T15:30:54.625485+00:00 [running]> on host 684187fd80f1
[2025-05-07T15:30:55.735+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_etl_dag
AIRFLOW_CTX_TASK_ID=transform_csv
AIRFLOW_CTX_EXECUTION_DATE=2025-05-07T15:30:54.625485+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-07T15:30:54.625485+00:00
[2025-05-07T15:30:55.741+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_lake_pipeline.py", line 15, in transform_csv
    df = pd.read_csv(input_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/example.csv'
[2025-05-07T15:30:55.756+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=csv_etl_dag, task_id=transform_csv, execution_date=20250507T153054, start_date=20250507T153055, end_date=20250507T153055
[2025-05-07T15:30:55.767+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task transform_csv ([Errno 2] No such file or directory: '/opt/airflow/data/example.csv'; 208)
[2025-05-07T15:30:55.795+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-07T15:30:55.813+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
